package com.lyxtera.axiom.api.parser;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import com.lyxtera.axiom.antlr.BusinessRuleBaseVisitor;
import com.lyxtera.axiom.antlr.BusinessRuleParser;
import com.lyxtera.axiom.antlr.BusinessRuleParser.BusinessActionListContext;
import com.lyxtera.axiom.api.model.BusinessAction;
import com.lyxtera.axiom.api.model.BusinessCheck;
import com.lyxtera.axiom.api.model.BusinessRule;
import com.lyxtera.axiom.api.model.Condition;
import com.lyxtera.axiom.api.model.RuleFunction;
import com.lyxtera.axiom.engine.RuleSet;
/**
 * Visitor implementation for parsing business rules.
 * <p>
 * This visitor traverses the parse tree generated by ANTLR and constructs a
 * {@link BusinessRule} object with the appropriate condition and actions.
 * It delegates the parsing of conditions and actions to specialized visitors.
 *
 * @param <K> The enum type to be used as context keys
 */
public class BusinessRuleVisitor<K extends Enum<K>> extends BusinessRuleBaseVisitor<BusinessRule<K>> {

    private final String ruleName;
    private final Map<String, BusinessCheck<K>> businessChecks;
    private final Map<String, BusinessAction<K>> businessActions;
    private final RuleSet.Metadata metadata;

    /**
     * Creates a new BusinessRuleVisitor with the specified rule name and business checks and actions.
     *
     * @param ruleName The name of the rule being parsed
     * @param businessChecks Map of business check implementations keyed by name
     * @param businessActions Map of business action implementations keyed by name
     */
    public BusinessRuleVisitor(String ruleName, Map<String, BusinessCheck<K>> businessChecks,
            Map<String, BusinessAction<K>> businessActions, RuleSet.Metadata metadata) {
        this.ruleName = ruleName;
        this.businessChecks = businessChecks;
        this.businessActions = businessActions;
        this.metadata = metadata;
    }

    /**
     * Visits a business rule node in the parse tree and constructs a {@link BusinessRule} object.
     * <p>
     * This method delegates the parsing of conditions to a {@link ConditionVisitor} and
     * the parsing of actions to an {@link OutcomeVisitor}.
     *
     * @param ctx The business rule context from the parse tree
     * @return A fully constructed BusinessRule object
     */
    @Override
    public BusinessRule<K> visitBusinessRule(BusinessRuleParser.BusinessRuleContext ctx) {
        ConditionVisitor<K> conditionVisitor = new ConditionVisitor<>(businessChecks, metadata);
        Condition<K> condition = null;

        if (ctx.expression() != null) {
            condition = conditionVisitor.visitExpression(ctx.expression());
        }

        OutcomeVisitor<K> outcomeVisitor = new OutcomeVisitor<>(businessActions, metadata);
        List<RuleFunction<K>> actions = new ArrayList<>();

        if (ctx.outcome() != null) {
            actions = outcomeVisitor.visitBusinessActionList((BusinessActionListContext) ctx.outcome());
        }

        return new BusinessRule<>(ruleName, condition, actions);
    }
}